### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by chartjes** [mozilla/PyFxA#60]
I am getting this warning when I run a pytest script that uses fxa.tests.utils.TestEmail account 

﻿﻿cannot collect test class 'TestEmailAccount' because it has a __init__ constructor

Running in this environment: platform darwin -- Python 3.6.3, pytest-3.3.2, py-1.5.2, pluggy-0.6.0

**Comment by rfk** [comment]
Hrm, I guess because this class has a name starting with "Test" then pytest thinks it should be a test, but it's just a helper class.

I've seen a few diffs around where they move from doing `from foo import TestLikeThing` to referencing it via lookup as `foo.TestLikeThing`, e.g.

  https://github.com/coala/coala/pull/3897/files

Maybe that will help in this case?  Otherwise we might have to rename the helper to `TemporaryEmailAccount` or something that looks less test-like.

**Comment by rfk** [comment]
Looks like we can also add `__test__ = False` on the class to make it ignored:

  https://github.com/pytest-dev/pytest/issues/1558

Please let me know if https://github.com/mozilla/PyFxA/pull/61 helps.
